version: '3'
services:
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./tmp/db:/var/lib/postgresql/data #MacOSの場合
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin-pass'
      POSTGRES_HOST: 'postgres'
      POSTGRES_PORT: 5432
    restart: always
  web:
    build: .
    image: rails
    container_name: 'web'
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    environment:
      VIRTUAL_PORT: 3000
    volumes:
      - .:/app
    depends_on:
      - postgres
    restart: always

